import { Tool } from '@modelcontextprotocol/sdk/types.js';
import * as fs from 'fs/promises';
import * as path from 'path';

const BLOCKED_PATHS = ['/etc/passwd', '/etc/shadow', '/root/.ssh', '/.ssh', '/.aws', '/.npm/_auth'];

function validatePath(inputPath: string): void {
  if (inputPath.includes('..') || inputPath.includes('~')) {
    throw new Error('Path traversal not allowed');
  }
  const resolved = path.resolve(inputPath);
  for (const blocked of BLOCKED_PATHS) {
    if (resolved.startsWith(blocked)) throw new Error(`Sensitive path not allowed: ${blocked}`);
  }
}

// ─────────────────────────────────────────────
// ADR TEMPLATE
// ─────────────────────────────────────────────
function generateAdrTemplate(context: string, decisionTitle: string): string {
  const now = new Date().toISOString().split('T')[0];
  const id = `ADR-${Math.floor(Math.random() * 900) + 100}`;
  return `# ${id}: ${decisionTitle}

**Status:** Proposed  
**Date:** ${now}  
**Context:** ${context}

## Context and Problem Statement

${context || 'Describe the situation that requires a decision.'}

## Decision Drivers

- Driver 1
- Driver 2
- Driver 3

## Options Considered

### Option 1: [Name]
**Description:**  
**Pros:**  
**Cons:**  

### Option 2: [Name]  
**Description:**  
**Pros:**  
**Cons:**  

## Decision Outcome

**Chosen option:** [Option X] — [brief justification]

## Consequences

### Positive
- Improved [aspect]
- Reduced [cost/complexity]

### Negative
- Increased [trade-off]

## References

- [Related ADR or documentation link]

---
*Generated by CodeBlueprint MCP Docs Generator*
`;
}

// ─────────────────────────────────────────────
// README TEMPLATE
// ─────────────────────────────────────────────
async function generateReadmeTemplate(projectPath: string): Promise<string> {
  validatePath(projectPath);
  const resolved = path.resolve(projectPath);
  let description = 'A project';
  let structure = '';

  try {
    const entries = await fs.readdir(resolved, { withFileTypes: true });
    const dirs = entries.filter(e => e.isDirectory()).map(e => e.name);
    const files = entries.filter(e => e.isFile()).map(e => e.name);
    structure = `## Project Structure\n\n\`\`\`\n${path.basename(resolved)}/\n${dirs.slice(0, 8).map(d => `├── ${d}/`).join('\n')}\n${files.slice(0, 8).map(f => `├── ${f}`).join('\n')}\n\`\`\`\n`;
    description = `> Auto-generated README for \`${path.basename(resolved)}\``;
  } catch {
    return `# ${path.basename(resolved)}\n\n${description}\n`;
  }

  return `# ${path.basename(resolved)}

${description}

${structure}
## Getting Started

\`\`\`bash
# Installation
npm install

# Development
npm run dev

# Build
npm run build
\`\`\`

## Usage

[Describe how to use the project]

## Configuration

[Configuration options]

## License

MIT
---
*Generated by CodeBlueprint MCP Docs Generator*
`;
}

// ─────────────────────────────────────────────
// API DOC TEMPLATE
// ─────────────────────────────────────────────
async function generateApiDoc(sourcePath: string, maxLines = 500): Promise<string> {
  validatePath(sourcePath);
  const resolved = path.resolve(sourcePath);
  let content = '';
  try {
    content = await fs.readFile(resolved, 'utf-8');
    const lines = content.split('\n').slice(0, maxLines);
    content = lines.join('\n');
  } catch (e: any) {
    throw new Error(`Cannot read file: ${e.message}`);
  }

  const filename = path.basename(resolved);
  const functions: string[] = [];
  const classes: string[] = [];
  const routes: string[] = [];

  // Extract function declarations (JS/TS)
  for (const line of content.split('\n')) {
    const fn = line.match(/^\s*(?:export\s+)?(?:async\s+)?function\s+(\w+)/);
    if (fn) functions.push(fn[1]);
    const cls = line.match(/^\s*(?:export\s+)?class\s+(\w+)/);
    if (cls) classes.push(cls[1]);
    const route = line.match(/[@](?:get|post|put|patch|delete)\s+['"]?(\/[^\s'"()]+)/);
    if (route) routes.push(route[1]);
  }

  return `# API Documentation: ${filename}

**File:** \`${sourcePath}\`  
**Generated:** ${new Date().toISOString().split('T')[0]}

## Overview

${classes.length ? `**Classes:** ${classes.join(', ')}` : ''}
${functions.length ? `**Functions:** ${functions.length} exported functions detected` : ''}
${routes.length ? `**Routes:** ${routes.join(', ')}` : ''}

## Code

\`\`\`typescript
${content}
\`\`\`

## Endpoints

${routes.length ? routes.map((r, i) => `${i + 1}. \`${r}\``).join('\n') : '_No HTTP routes detected in this file._'}

## Usage Example

\`\`\`typescript
// Import the module
import { ${classes[0] || 'module'} } from '${filename.replace(/\.[^.]+$/, '')}';

// ${functions[0] ? `Call a function: ${functions[0]}()` : 'Use the exported API'}
\`\`\`

---
*Generated by CodeBlueprint MCP Docs Generator*
`;
}

// ─────────────────────────────────────────────
// CODEBASE AUDIT
// ─────────────────────────────────────────────
async function auditCodebase(rootPath: string): Promise<string> {
  validatePath(rootPath);
  const resolved = path.resolve(rootPath);
  const stats = { totalFiles: 0, totalDirs: 0, languages: {} as Record<string, number> };
  const findings: string[] = [];

  async function scan(dir: string, depth = 0): Promise<void> {
    if (depth > 4) return;
    try {
      const entries = await fs.readdir(dir, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.name === 'node_modules' || entry.name === '.git' || entry.name === 'dist' || entry.name.startsWith('.')) continue;
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          stats.totalDirs++;
          await scan(full, depth + 1);
        } else {
          stats.totalFiles++;
          const ext = path.extname(entry.name).slice(1) || 'no-ext';
          stats.languages[ext] = (stats.languages[ext] || 0) + 1;
        }
      }
    } catch { /* skip inaccessible */ }
  }

  await scan(resolved);

  // Check for documentation gaps
  const hasReadme = (await fs.readdir(resolved)).some(f => f.toLowerCase() === 'readme.md');
  const hasPkg = (await fs.readdir(resolved)).some(f => f === 'package.json');
  const hasTsConfig = (await fs.readdir(resolved)).some(f => f === 'tsconfig.json');
  const hasGitignore = (await fs.readdir(resolved)).some(f => f === '.gitignore');

  if (!hasReadme) findings.push('- Missing README.md');
  if (!hasPkg) findings.push('- No package.json found (not a Node.js project?)');
  if (!hasTsConfig && hasPkg) findings.push('- No tsconfig.json (TypeScript project without config?)');
  if (!hasGitignore) findings.push('- No .gitignore');
  if (stats.totalFiles > 50 && !hasReadme) findings.push('- Large codebase without README — high documentation debt');
  if (!stats.languages['md']) findings.push('- No markdown documentation files found');

  return JSON.stringify({
    summary: {
      totalFiles: stats.totalFiles,
      totalDirectories: stats.totalDirs,
      languages: stats.languages,
      hasReadme,
    },
    documentationStatus: {
      readme: hasReadme ? 'present' : 'MISSING',
      packageJson: hasPkg ? 'present' : 'not found',
      gitignore: hasGitignore ? 'present' : 'MISSING',
      tsConfig: hasTsConfig ? 'present' : 'not applicable',
    },
    recommendations: findings.length
      ? findings
      : ['- Codebase appears well organized. Consider adding architecture documentation (ADRs) for key decisions.'],
    generatedBy: 'CodeBlueprint mcp-docs-generator v0.1.0',
  }, null, 2);
}

// ─────────────────────────────────────────────
// TOOL DEFINITIONS
// ─────────────────────────────────────────────
export function listDocsTools(): Tool[] {
  return [
    {
      name: 'docs_generate_adr',
      description: 'Generate an Architecture Decision Record (ADR) from project context and decision description',
      inputSchema: {
        type: 'object',
        properties: {
          title: { type: 'string', description: 'Title of the architectural decision (e.g. "Choose PostgreSQL as primary database")' },
          context: { type: 'string', description: 'Background context, problem statement, or project description to base the ADR on' },
        },
        required: ['title'],
      },
    },
    {
      name: 'docs_generate_readme',
      description: 'Generate a README.md file content from a project directory structure',
      inputSchema: {
        type: 'object',
        properties: {
          project_path: { type: 'string', description: 'Path to the project root directory' },
        },
        required: ['project_path'],
      },
    },
    {
      name: 'docs_generate_api_doc',
      description: 'Generate API documentation from a source code file',
      inputSchema: {
        type: 'object',
        properties: {
          source_path: { type: 'string', description: 'Path to the source file (TypeScript/JavaScript)' },
          max_lines: { type: 'number', description: 'Maximum lines to read (default 500)' },
        },
        required: ['source_path'],
      },
    },
    {
      name: 'docs_audit_codebase',
      description: 'Scan a codebase directory and return documentation coverage analysis with recommendations',
      inputSchema: {
        type: 'object',
        properties: {
          root_path: { type: 'string', description: 'Path to the project root' },
        },
        required: ['root_path'],
      },
    },
  ];
}

// ─────────────────────────────────────────────
// HANDLER
// ─────────────────────────────────────────────
export async function handleDocsTool(
  name: string,
  args: any
): Promise<{ content: Array<{ type: string; text: string }>; isError?: boolean }> {
  try {
    switch (name) {
      case 'docs_generate_adr': {
        const { title, context = '' } = args;
        if (!title || title.length > 200) throw new Error('title must be 1-200 characters');
        const result = generateAdrTemplate(context, title);
        return { content: [{ type: 'text', text: result }] };
      }

      case 'docs_generate_readme': {
        const { project_path } = args;
        if (!project_path) throw new Error('project_path is required');
        validatePath(project_path);
        const result = await generateReadmeTemplate(project_path);
        return { content: [{ type: 'text', text: result }] };
      }

      case 'docs_generate_api_doc': {
        const { source_path, max_lines = 500 } = args;
        if (!source_path) throw new Error('source_path is required');
        const safeLines = Math.min(Math.max(1, Number(max_lines) || 500), 2000);
        const result = await generateApiDoc(source_path, safeLines);
        return { content: [{ type: 'text', text: result }] };
      }

      case 'docs_audit_codebase': {
        const { root_path } = args;
        if (!root_path) throw new Error('root_path is required');
        const result = await auditCodebase(root_path);
        return { content: [{ type: 'text', text: result }] };
      }

      default:
        return { content: [{ type: 'text', text: `Unknown docs tool: ${name}` }], isError: true };
    }
  } catch (error: any) {
    return { content: [{ type: 'text', text: `Error: ${error.message}` }], isError: true };
  }
}
